### ISSUE TITLE
鑽转换有问题，应该是钻

### ISSUE THREAD

**Issue by MxCen** [xiaoxinpro/ChineseSubtitleConversionTool#1]
鑽转换有问题，应该是钻

**Comment by xiaoxinpro** [comment]
该问题以修复，请下载使用最新版本 [ChineseSubtitleConversionTool.exe](https://github.com/xiaoxinpro/ChineseSubtitleConversionTool/raw/master/ChineseSubtitleConversionTool/bin/Debug/ChineseSubtitleConversionTool.exe)
