### ISSUE TITLE
优化古文字转换模式下部分繁体字未进行转换

### ISSUE THREAD

**Issue by acientdragon** [xiaoxinpro/ChineseSubtitleConversionTool#11]
发现在优化古文字转换模式下，部分繁体字未进行转换，暂时发现以下繁体字未转换：鬆、闆、唸、閒、囉、傢、託、嚥、捲、麵、鑑。而如果使用高精度模式转换时，输出文件会添加多余的空行。

**Comment by xiaoxinpro** [comment]
感谢反馈，优化古文字转换已经修复，[ChineseSubtitleConversionTool.exe](https://github.com/xiaoxinpro/ChineseSubtitleConversionTool/raw/master/ChineseSubtitleConversionTool/bin/Debug/ChineseSubtitleConversionTool.exe)
