### ISSUE TITLE
批量转换使用高精度模式会出现文件0kb的情况，快速模式“麽”."後"无法转换

### ISSUE THREAD

**Issue by yanxin152133** [xiaoxinpro/ChineseSubtitleConversionTool#13]
批量转换使用高精度模式会出现文件0kb
![image](https://user-images.githubusercontent.com/43341537/164283323-c83d75b9-a638-4e90-99c7-741aafb0c912.png)

快速模式“麽”,"後"无法转换
![image](https://user-images.githubusercontent.com/43341537/164283533-fcb8fe45-7daf-4edd-8d3c-5bcd638e3f82.png)
![image](https://user-images.githubusercontent.com/43341537/164283781-39116bea-1d8d-4fbd-961d-06681b3ec153.png)

**Comment by xiaoxinpro** [comment]
1. 高精度模式必须安装微软的Office才可以使用，如果你安装的wps等第三方Office则转换失败。
2. 快速模拟式调用的vbs组件，转换速度快单准确性低，建议还用优化古文字模式。
