### ISSUE TITLE
能否去掉界面的说明文档或可以保持清空的界面设置

### ISSUE THREAD

**Issue by xelc** [xiaoxinpro/ChineseSubtitleConversionTool#14]
电脑里有些繁体名称的文件，自从用了大佬的工具，个人的使用习惯更多是通过别人提起的名称复制或输入转换后用Everything搜索文件。
新版界面文字密密麻麻的，每次打开都要清空一遍说明文档，略显麻烦。
可以单独建一份说明文档，保持界面的清爽。

**Comment by xiaoxinpro** [comment]
软件右上角有清空按钮，点击一下就可以清空文本内容。
