### ISSUE TITLE
支持的编码不够多，导致转换后的字幕文件无法被播放器使用

### ISSUE THREAD

**Issue by XiaofengdiZhu** [xiaoxinpro/ChineseSubtitleConversionTool#16]
[[NOP] Iryu - Team Medical Dragon (Season 2) - 01 [1080p].ssa.txt](https://github.com/xiaoxinpro/ChineseSubtitleConversionTool/files/8628280/NOP.Iryu.-.Team.Medical.Dragon.Season.2.-.01.1080p.ssa.txt)
例如此附件，编码是UTF-16 LE with BOM，软件中选择UTF-16，转换出来的是UTF-16 LE，PotPlayer就无法识别了

**Comment by xiaoxinpro** [comment]
这种情况你可以选择UTF-8转换，结果是可以识别的。

**Comment by XiaofengdiZhu** [comment]
> 这种情况你可以选择UTF-8转换，结果是可以识别的。

原来界面上设置的编码是输出编码，而不是输入编码，原来如此，谢谢
