### ISSUE TITLE
希望增加一键复制功能

### ISSUE THREAD

**Issue by tulip33** [xiaoxinpro/ChineseSubtitleConversionTool#2]
希望增加个复制按钮，将转换后的文字复制到剪贴板

**Comment by xiaoxinpro** [comment]
非常好的建议，后续将增加一键复制按钮。

**Comment by xiaoxinpro** [comment]
最新版本已增加该功能[ChineseSubtitleConversionTool.exe](https://github.com/xiaoxinpro/ChineseSubtitleConversionTool/raw/master/ChineseSubtitleConversionTool/bin/Debug/ChineseSubtitleConversionTool.exe)
