### ISSUE TITLE
报毒

### ISSUE THREAD

**Issue by Fr0stsilver** [xiaoxinpro/ChineseSubtitleConversionTool#20]
开发版本：[ChineseSubtitleConversionTool.exe](https://github.com/xiaoxinpro/ChineseSubtitleConversionTool/raw/master/ChineseSubtitleConversionTool/bin/Debug/ChineseSubtitleConversionTool.exe) [扫描报告](https://www.virustotal.com/gui/file/b0130090de1dd8319dd2c6be86b8cb1957adad4f8ea1576a1eedfaeeac27fe5f)
![image](https://user-images.githubusercontent.com/54761496/204074797-dec780ec-4bc3-4650-a7eb-085b4430ed2e.png)
Release Apr 21: 繁体简体字幕转换工具 V0.4.3.61 [ChineseSubtitleConversionTool.zip](https://github.com/xiaoxinpro/ChineseSubtitleConversionTool/releases/download/V0.4.3.61/ChineseSubtitleConversionTool.zip) [扫描报告](https://www.virustotal.com/gui/file/86fe5e7a182a1269cb59624952532c41914952c2469f31aa091dd7a8a532a096)
![image](https://user-images.githubusercontent.com/54761496/204074882-e4fa8851-3fbe-46f6-ada3-21f56fec8d14.png)

**Comment by xiaoxinpro** [comment]
无语，代码是全部开源的，你如果不放心就自己编译吧
