### ISSUE TITLE
未转换繁体的字

### ISSUE THREAD

**Issue by Gloryandel** [xiaoxinpro/ChineseSubtitleConversionTool#22]
永恒-永恆

**Comment by Gloryandel** [comment]
拚命

**Comment by Hellohistory** [comment]
这个项目好像使用的是列表来转换的，列表没有收录的话好像没办法转换

**Comment by Gloryandel** [comment]
那就没办法了😂，不过能转换大部分就很不错了

**Comment by xiaoxinpro** [comment]
只有`优化古文字`的转换模式是匹配的，用`高精度`转换的结果会比较精准

**Comment by xiaoxinpro** [comment]
以修复`恆`和`拚`的转换，请下载开发版本：[ChineseSubtitleConversionTool.exe](https://github.com/xiaoxinpro/ChineseSubtitleConversionTool/raw/master/ChineseSubtitleConversionTool/bin/Debug/ChineseSubtitleConversionTool.exe)

**Comment by Gloryandel** [comment]
> 以修复`恆`和`拚`的转换，请下载开发版本：[ChineseSubtitleConversionTool.exe](https://github.com/xiaoxinpro/ChineseSubtitleConversionTool/raw/master/ChineseSubtitleConversionTool/bin/Debug/ChineseSubtitleConversionTool.exe)

原来还再维护的,加油!这可以说是字幕转换的独苗啊!😂👍

**Comment by Hellohistory** [comment]
可以试试把核心代码更换成OpenCC，能转换的更多

Gloryandel ***@***.***> 于2023年5月7日周日 13:10写道：

**Comment by xiaoxinpro** [comment]
@Hellohistory 使用`高精度`转换已经可以满足字幕转换的需求了，后面不会再考虑增加内核了

**Comment by Hellohistory** [comment]
哦哦哦，好的
