### ISSUE TITLE
未转换繁体的字

### ISSUE THREAD

**Issue by fgr178707** [xiaoxinpro/ChineseSubtitleConversionTool#25]
牠 它

**Comment by xiaoxinpro** [comment]
以修复，下载开发版本：[ChineseSubtitleConversionTool.exe](https://github.com/xiaoxinpro/ChineseSubtitleConversionTool/raw/master/ChineseSubtitleConversionTool/bin/Debug/ChineseSubtitleConversionTool.exe)
