### ISSUE TITLE
请问工具会考虑开源嘛

### ISSUE THREAD

**Issue by elliott10** [xiaoxinpro/ChineseSubtitleConversionTool#27]
请问该繁简转换工具会考虑开源嘛？

**Comment by xiaoxinpro** [comment]
不就是开源的嘛

---- 回复的原邮件 ----
| 发件人 | Luoyuan ***@***.***> |
| 发送日期 | 2023年12月02日 15:43 |
| 收件人 | xiaoxinpro/ChineseSubtitleConversionTool ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [xiaoxinpro/ChineseSubtitleConversionTool] 请问工具会考虑开源嘛 (Issue #27) |

请问该繁简转换工具会考虑开源嘛？

**Comment by elliott10** [comment]
哈哈 好！谢谢作者的编程成果👍
