### ISSUE TITLE
繁体转简体时所有的“妳”字没有转换成“你”

### ISSUE THREAD

**Issue by TCBOMC** [xiaoxinpro/ChineseSubtitleConversionTool#29]
[恋爱研究所.zip](https://github.com/xiaoxinpro/ChineseSubtitleConversionTool/files/14393676/default.zip)
使用高精度模式批量转换后半季的字幕“妳”字都没换。左侧为原字幕，右侧为这个软件转换后的字幕，中间为24TT软件转换后的字幕
![屏幕截图 2024-02-24 200321](https://github.com/xiaoxinpro/ChineseSubtitleConversionTool/assets/43884501/b304d446-fb41-4f83-89b0-edde67f88edf)

**Comment by xiaoxinpro** [comment]
高精度模式调用的是Office语义转换，如果比较在意这种问题，可以再进行一次`优化古文字`转换。
