### ISSUE TITLE
无法识别或设置源文件的编码格式

### ISSUE THREAD

**Issue by nov12** [xiaoxinpro/ChineseSubtitleConversionTool#30]
源文件时Big5，无法转换，必须先手动转换编码格式才能进行简繁转换。不然全是乱码

**Comment by xiaoxinpro** [comment]
麻烦提供一下你的源文件

**Comment by nov12** [comment]
[The.West.Wing.S01-07.1080p.WEB-DL.AAC2.0.H.264-NTb.官中.zip](https://github.com/xiaoxinpro/ChineseSubtitleConversionTool/files/14834108/The.West.Wing.S01-07.1080p.WEB-DL.AAC2.0.H.264-NTb.zip)

我用别的小工具已经转了编码格式，
工具地址，给有同样需求的人 https://www.chinesecj.com/forum/forum.php?mod=viewthread&tid=577

**Comment by xiaoxinpro** [comment]
增加了输入编码选择功能，可以下载开发版本：[ChineseSubtitleConversionTool.exe](https://github.com/xiaoxinpro/ChineseSubtitleConversionTool/raw/master/ChineseSubtitleConversionTool/bin/Debug/ChineseSubtitleConversionTool.exe)
