### ISSUE TITLE
能否对输出文件名加一个特性

### ISSUE THREAD

**Issue by bianfanbo** [xiaoxinpro/ChineseSubtitleConversionTool#32]
我使用这个软件主要是用于繁体的动画字幕，这些字幕会使用“.tc”来标注是繁体字幕文件
就是可不可以将字幕文件结尾处的“.tc”自动替换为“.sc”
虽然这个小要求其它重命名软件可以做到，但还是希望能做个可选性质的支持

**Comment by xiaoxinpro** [comment]
可以的，软件的`文件名样式`可以修改输出的文件名，默认是`{name}.chs{exten}`，你可以改为`{name}.sc`
