### ISSUE TITLE
在转换srt文件的时候,文本框里似乎只能装646条字幕, 或者1h06时长的字幕.多出的字幕无法输入

### ISSUE THREAD

**Issue by gheougje** [xiaoxinpro/ChineseSubtitleConversionTool#7]
![issue1](https://user-images.githubusercontent.com/83564645/137636158-72dc796c-ade2-417a-928f-4e12caa7d045.png)
![issue2](https://user-images.githubusercontent.com/83564645/137636159-b09bdf37-5729-47e2-86e8-e14cfa197d58.png)

**Comment by xiaoxinpro** [comment]
是否可以提供一下你的字幕文件用于测试？

**Comment by xiaoxinpro** [comment]
BUG已修复，[ChineseSubtitleConversionTool.exe](https://github.com/xiaoxinpro/ChineseSubtitleConversionTool/raw/master/ChineseSubtitleConversionTool/bin/Debug/ChineseSubtitleConversionTool.exe)
