### ISSUE TITLE
高精度无法使用

### ISSUE THREAD

**Issue by photkey** [xiaoxinpro/ChineseSubtitleConversionTool#8]
![image](https://user-images.githubusercontent.com/60434581/147872123-8b057393-0c9e-44e3-9bd1-b3263a67307c.png)

![image](https://user-images.githubusercontent.com/60434581/147872220-9785e929-e1bf-4377-b24b-adff9bddb397.png)

系统：Windows 11，不知道是不是跟系统版本有关。开发版 高精度 模式不能用，稳定版，没有高精度模式。

**Comment by murasame-chan** [comment]
我也想知道为什么我用不了高精度模式，我也是win11，现在还有电脑不是自带office的吗，但是我高精度的按钮也是灰的，我不知道为什么把这个问题给关闭了，根本没有解决问题，放弃这个工具了，呵呵
