### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by xivi1839** [xiaoxinpro/ChineseSubtitleConversionTool#9]
下面的转换选项设置可以由用户个人喜欢自由设置默认的吗，我喜欢用高精度的，每次打开软件默认都是优化古文字

**Comment by xiaoxinpro** [comment]
[ChineseSubtitleConversionTool](https://github.com/xiaoxinpro/ChineseSubtitleConversionTool) 目标是纯绿色软件，不打算在硬盘中写入数据（包括配置信息）；不过后期会考虑将高精度设为默认设置（前提是高精度可用）。

**Comment by xivi1839** [comment]
其实也可以保存本地配置也行呀，就是我直接第一次设置默认什么以后打开软件就什么，也不错

**Comment by xivi1839** [comment]
高精度有个缺点就是，分段的句子，会自动密集到一块去，

比如这样：
当穿越过来的卢克蒙着头，

被帝国密探拿着一把枪指着脑袋的时候，

他决定撒一个谎。

于是他就成了金盾帝国海角区密情局的探长。

熟知剧情的卢克只想在这个即将混乱的世界里保命

**Comment by xiaoxinpro** [comment]
> 高精度有个缺点就是，分段的句子，会自动密集到一块去，
> 
> 比如这样： 当穿越过来的卢克蒙着头，
> 
> 被帝国密探拿着一把枪指着脑袋的时候，
> 
> 他决定撒一个谎。
> 
> 于是他就成了金盾帝国海角区密情局的探长。
> 
> 熟知剧情的卢克只想在这个即将混乱的世界里保命

问题已修复：[ChineseSubtitleConversionTool.exe](https://github.com/xiaoxinpro/ChineseSubtitleConversionTool/raw/master/ChineseSubtitleConversionTool/bin/Debug/ChineseSubtitleConversionTool.exe)
